/**
 * Presets data model and default "Vibe Code" preset.
 * Maps to .shimwrappercheckrc (SHIM_ENFORCE_COMMANDS, SHIM_HOOK_COMMANDS, etc.).
 */
import { getCheckRole } from "./checks";

export type ProviderId = "supabase" | "git";

export const SUPABASE_COMMAND_IDS = ["functions", "db", "migration", "push"] as const;
export const GIT_COMMAND_IDS = ["push", "commit", "merge", "rebase"] as const;

export type SupabaseCommandId = (typeof SUPABASE_COMMAND_IDS)[number];
export type GitCommandId = (typeof GIT_COMMAND_IDS)[number];

export interface SupabaseCommands {
  enforce: SupabaseCommandId[];
  hook: SupabaseCommandId[];
}
export interface GitCommands {
  enforce: GitCommandId[];
}

export interface Preset {
  id: string;
  name: string;
  providers: ProviderId[];
  supabase?: SupabaseCommands;
  git?: GitCommands;
  autoPush: boolean;
}

export interface CheckToggles {
  lint: boolean;
  prettier: boolean;
  typecheck: boolean;
  checkMockData: boolean;
  testRun: boolean;
  projectRules: boolean;
  npmAudit: boolean;
  viteBuild: boolean;
  snyk: boolean;
  denoFmt: boolean;
  denoLint: boolean;
  denoAudit: boolean;
  aiReview: boolean;
  updateReadme: boolean;
  sast: boolean;
  architecture: boolean;
  complexity: boolean;
  mutation: boolean;
  e2e: boolean;
}

/** Per-check options (persisted in presets JSON and written to rc as env where supported) */
export interface CheckSettings {
  npmAudit?: { auditLevel?: string };
  aiReview?: { timeoutSec?: number; diffLimitBytes?: number; minRating?: number; reviewDir?: string };
  healthPing?: { defaultFunction?: string; healthFunctions?: string; healthPaths?: string; projectRef?: string };
  edgeLogs?: { defaultFunction?: string; logFunctions?: string; logLimit?: number };
}

export interface SettingsData {
  presets: Preset[];
  activePresetId: string;
  checkToggles: CheckToggles;
  checkSettings?: CheckSettings;
  checkOrder?: string[];
}

const VIBE_CODE_ID = "vibe-code";

/** By default no check runs; user adds checks to My Shim to enable them. */
export const DEFAULT_CHECK_TOGGLES: CheckToggles = {
  lint: false,
  prettier: false,
  typecheck: false,
  checkMockData: false,
  testRun: false,
  projectRules: false,
  npmAudit: false,
  viteBuild: false,
  snyk: false,
  denoFmt: false,
  denoLint: false,
  denoAudit: false,
  aiReview: false,
  updateReadme: false,
  sast: false,
  architecture: false,
  complexity: false,
  mutation: false,
  e2e: false,
};

export const DEFAULT_VIBE_CODE_PRESET: Preset = {
  id: VIBE_CODE_ID,
  name: "Vibe Code",
  providers: ["supabase", "git"],
  supabase: {
    enforce: ["functions", "db", "migration"],
    hook: ["functions", "db", "migration"],
  },
  git: {
    enforce: ["push"],
  },
  autoPush: true,
};

/** Default: no checks in My Shim (all in Check Library). */
export const DEFAULT_SETTINGS: SettingsData = {
  presets: [DEFAULT_VIBE_CODE_PRESET],
  activePresetId: VIBE_CODE_ID,
  checkToggles: DEFAULT_CHECK_TOGGLES,
  checkOrder: [],
};

/** Build .shimwrappercheckrc content from active preset + check toggles */
export function buildRcContent(settings: SettingsData): string {
  const preset = settings.presets.find((p) => p.id === settings.activePresetId) ?? DEFAULT_VIBE_CODE_PRESET;
  const lines: string[] = ["# shimwrappercheck config (generated by dashboard)"];

  if (preset.providers.includes("supabase") && preset.supabase) {
    lines.push(`SHIM_ENFORCE_COMMANDS="${preset.supabase.enforce.join(",")}"`);
    lines.push(`SHIM_HOOK_COMMANDS="${preset.supabase.hook.join(",")}"`);
    lines.push(`SHIM_AUTO_PUSH=${preset.autoPush ? 1 : 0}`);
  }
  if (preset.providers.includes("git") && preset.git) {
    lines.push(`SHIM_GIT_ENFORCE_COMMANDS="${preset.git.enforce.join(",")}"`);
  }

  const t = settings.checkToggles;
  const frontendAllOff =
    !t.lint &&
    !t.prettier &&
    !t.typecheck &&
    !t.checkMockData &&
    !t.testRun &&
    !t.projectRules &&
    !t.npmAudit &&
    !t.viteBuild &&
    !t.snyk &&
    !t.updateReadme;
  const backendAllOff = !t.denoFmt && !t.denoLint && !t.denoAudit;
  const args: string[] = [];
  if (frontendAllOff) args.push("--no-frontend");
  if (backendAllOff) args.push("--no-backend");
  if (!t.aiReview) args.push("--no-ai-review");
  if (!t.sast) args.push("--no-sast");
  if (!t.architecture) args.push("--no-architecture");
  if (!t.complexity) args.push("--no-complexity");
  if (!t.mutation) args.push("--no-mutation");
  if (!t.e2e) args.push("--no-e2e");
  if (args.length) lines.push(`SHIM_CHECKS_ARGS="${args.join(" ")}"`);

  const order = settings.checkOrder ?? [];
  type CheckId = import("./checks").CheckId;
  const enforceOrder = order.filter((id) => getCheckRole(id as CheckId) === "enforce");
  const hookOrder = order.filter((id) => getCheckRole(id as CheckId) === "hook");
  if (enforceOrder.length) lines.push(`SHIM_CHECK_ORDER="${enforceOrder.join(",")}"`);
  lines.push(`SHIM_HOOK_CHECK_ORDER="${hookOrder.join(",")}"`);

  lines.push(`SHIM_RUN_LINT=${t.lint ? 1 : 0}`);
  lines.push(`SHIM_RUN_PRETTIER=${t.prettier ? 1 : 0}`);
  lines.push(`SHIM_RUN_TYPECHECK=${t.typecheck ? 1 : 0}`);
  lines.push(`SHIM_RUN_CHECK_MOCK_DATA=${t.checkMockData ? 1 : 0}`);
  lines.push(`SHIM_RUN_TEST_RUN=${t.testRun ? 1 : 0}`);
  lines.push(`SHIM_RUN_PROJECT_RULES=${t.projectRules ? 1 : 0}`);
  lines.push(`SHIM_RUN_NPM_AUDIT=${t.npmAudit ? 1 : 0}`);
  lines.push(`SHIM_RUN_VITE_BUILD=${t.viteBuild ? 1 : 0}`);
  lines.push(`SHIM_RUN_SNYK=${t.snyk ? 1 : 0}`);
  lines.push(`SHIM_RUN_DENO_FMT=${t.denoFmt ? 1 : 0}`);
  lines.push(`SHIM_RUN_DENO_LINT=${t.denoLint ? 1 : 0}`);
  lines.push(`SHIM_RUN_DENO_AUDIT=${t.denoAudit ? 1 : 0}`);
  lines.push(`SHIM_RUN_UPDATE_README=${t.updateReadme ? 1 : 0}`);

  const cs = settings.checkSettings;
  if (!t.snyk) lines.push("SKIP_SNYK=1");
  if (cs?.npmAudit?.auditLevel) lines.push(`SHIM_AUDIT_LEVEL="${cs.npmAudit.auditLevel}"`);
  if (cs?.aiReview?.timeoutSec != null) lines.push(`SHIM_AI_TIMEOUT_SEC=${cs.aiReview.timeoutSec}`);
  if (cs?.aiReview?.diffLimitBytes != null) lines.push(`SHIM_AI_DIFF_LIMIT_BYTES=${cs.aiReview.diffLimitBytes}`);
  if (cs?.aiReview?.minRating != null) lines.push(`SHIM_AI_MIN_RATING=${cs.aiReview.minRating}`);
  if (cs?.aiReview?.reviewDir) lines.push(`SHIM_AI_REVIEW_DIR="${cs.aiReview.reviewDir}"`);
  const defaultFn = cs?.healthPing?.defaultFunction || cs?.edgeLogs?.defaultFunction;
  if (defaultFn) lines.push(`SHIM_DEFAULT_FUNCTION="${defaultFn}"`);
  if (cs?.healthPing?.healthFunctions) lines.push(`SHIM_HEALTH_FUNCTIONS="${cs.healthPing.healthFunctions}"`);
  if (cs?.healthPing?.healthPaths) lines.push(`SHIM_HEALTH_PATHS="${cs.healthPing.healthPaths}"`);
  if (cs?.healthPing?.projectRef) lines.push(`SUPABASE_PROJECT_REF="${cs.healthPing.projectRef}"`);
  if (cs?.edgeLogs?.logFunctions) lines.push(`SHIM_LOG_FUNCTIONS="${cs.edgeLogs.logFunctions}"`);
  if (cs?.edgeLogs?.logLimit != null) lines.push(`SHIM_LOG_LIMIT=${cs.edgeLogs.logLimit}`);

  return lines.join("\n") + "\n";
}
