/**
 * Presets data model and default "Vibe Code" preset.
 * Maps to .shimwrappercheckrc (SHIM_ENFORCE_COMMANDS, SHIM_HOOK_COMMANDS, etc.).
 */

export type ProviderId = "supabase" | "git";

export const SUPABASE_COMMAND_IDS = [
  "functions",
  "db",
  "migration",
  "push",
] as const;
export const GIT_COMMAND_IDS = ["push", "commit", "merge", "rebase"] as const;

export type SupabaseCommandId = (typeof SUPABASE_COMMAND_IDS)[number];
export type GitCommandId = (typeof GIT_COMMAND_IDS)[number];

export interface SupabaseCommands {
  enforce: SupabaseCommandId[];
  hook: SupabaseCommandId[];
}
export interface GitCommands {
  enforce: GitCommandId[];
}

export interface Preset {
  id: string;
  name: string;
  providers: ProviderId[];
  supabase?: SupabaseCommands;
  git?: GitCommands;
  autoPush: boolean;
}

export interface CheckToggles {
  frontend: boolean;
  backend: boolean;
  aiReview: boolean;
  sast: boolean;
  architecture: boolean;
  complexity: boolean;
  mutation: boolean;
  e2e: boolean;
}

export interface SettingsData {
  presets: Preset[];
  activePresetId: string;
  checkToggles: CheckToggles;
}

const VIBE_CODE_ID = "vibe-code";

export const DEFAULT_CHECK_TOGGLES: CheckToggles = {
  frontend: true,
  backend: true,
  aiReview: true,
  sast: true,
  architecture: true,
  complexity: true,
  mutation: true,
  e2e: true,
};

export const DEFAULT_VIBE_CODE_PRESET: Preset = {
  id: VIBE_CODE_ID,
  name: "Vibe Code",
  providers: ["supabase", "git"],
  supabase: {
    enforce: ["functions", "db", "migration"],
    hook: ["functions", "db", "migration"],
  },
  git: {
    enforce: ["push"],
  },
  autoPush: true,
};

export const DEFAULT_SETTINGS: SettingsData = {
  presets: [DEFAULT_VIBE_CODE_PRESET],
  activePresetId: VIBE_CODE_ID,
  checkToggles: DEFAULT_CHECK_TOGGLES,
};

/** Build .shimwrappercheckrc content from active preset + check toggles */
export function buildRcContent(settings: SettingsData): string {
  const preset = settings.presets.find((p) => p.id === settings.activePresetId) ?? DEFAULT_VIBE_CODE_PRESET;
  const lines: string[] = ["# shimwrappercheck config (generated by dashboard)"];

  if (preset.providers.includes("supabase") && preset.supabase) {
    lines.push(`SHIM_ENFORCE_COMMANDS="${preset.supabase.enforce.join(",")}"`);
    lines.push(`SHIM_HOOK_COMMANDS="${preset.supabase.hook.join(",")}"`);
    lines.push(`SHIM_AUTO_PUSH=${preset.autoPush ? 1 : 0}`);
  }
  if (preset.providers.includes("git") && preset.git) {
    lines.push(`SHIM_GIT_ENFORCE_COMMANDS="${preset.git.enforce.join(",")}"`);
  }

  const args: string[] = [];
  if (!settings.checkToggles.frontend) args.push("--no-frontend");
  if (!settings.checkToggles.backend) args.push("--no-backend");
  if (!settings.checkToggles.aiReview) args.push("--no-ai-review");
  if (!settings.checkToggles.sast) args.push("--no-sast");
  if (!settings.checkToggles.architecture) args.push("--no-architecture");
  if (!settings.checkToggles.complexity) args.push("--no-complexity");
  if (!settings.checkToggles.mutation) args.push("--no-mutation");
  if (!settings.checkToggles.e2e) args.push("--no-e2e");
  if (args.length) lines.push(`SHIM_CHECKS_ARGS="${args.join(" ")}"`);

  return lines.join("\n") + "\n";
}
